<!-- Privacy Policy Template -->
<div class="subpage-header">
	<h1>Privacy Policy</h1>
	<p>We take your privacy seriously.</p>
</div>
<div class="subpage-content">
	<h3>Updated February 27, 2014</h3>
	<p>Careeralerts.com ("Career Alerts") takes your privacy very seriously and has created this Privacy Policy in order to disclose its use of consumer data collected about you. You may contact Career Alerts at 2312 Park Ave #408, Tustin, CA 92782 USA or via our <a href="#contact">contact form</a>.</p>
	<p>By using the Career Alerts website, or submitting information to us by other means, you are subjecting your information to the practices outlined in this Privacy Policy. This Privacy Policy covers Career Alerts's treatment of personal information that we collect when you are on Career Alerts's website and when you use Career Alerts's services. This policy does not apply to the practices of third parties that Career Alerts does not own or control, including websites that we may link to, or to individuals that Career Alerts does not employ or manage.</p>
	<h3>Privacy Policy Updates</h3>
	<p>Due to the Internet's rapidly evolving nature, Career Alerts may need to update this Privacy Policy from time to time. If so, Career Alerts will post its updated Privacy Policy on our website located at www.careeralerter.com. Career Alerts encourages you to review this Privacy Policy regularly for any changes. Your continued use of this site and/or continued provision of personally identifiable information to Career Alerts will be subject to the then current Privacy Policy.</p>
	<h3>Information Collection</h3>
	<p>Career Alerts may collect or receive information about you when you register or submit information, including, but not limited to, username, password, first and last name, email address, street address, gender, occupation, interests, resume and contents thereof, job search history, and any other data included in a submitted profile, resume, or search. Career Alerts also collects information on the pages you access and other information you may volunteer, such as survey information, ratings, reviews, questions, and answers. Career Alerts may also record actions taken on our site including, but not limited to, clicks, page views, IP address, and search queries. Career Alerts may store this information in its equipment or the equipment of third party technology providers.</p>
	<h3>Use of Information</h3>
	<p>Career Alerts, or companies we partner with, may contact you based on your interests such as job postings and career development opportunities. Career Alerts's site may require you to provide Career Alerts with contact information (such as your name and email address) and demographic information. Career Alerts may use your contact information to (a) send you job alerts; (b) create an account; or (c) send you information about Career Alerts and promotional material from some of Career Alerts's partners. Your contact information is also used to contact you when necessary. Career Alerts may use demographic and/or profile data, including but not limited to search history, to tailor your experience on Career Alerts's site, show you content that Career Alerts thinks you may be interested in, and display content according to your preferences. </p>
	<p>To the extent you upload a resume, Career Alerts may make the resume and other personal information contained therein available to third parties, including but not limited to employers and search engines. This means that the personal information contained in your resume can be viewed by third parties and you may receive unsolicited contact from third parties unaffiliated with Career Alerts. Career Alerts will make reasonable effort to safeguard the use of your personal information by third parties in accordance with this Privacy Policy. Career Alerts reserves the right to disclose any information as required by law. </p>
	<p>We may use other companies as necessary to perform services necessary to our operations. In the course of providing these services, those companies may have access to your personal information in accordance with this Privacy Policy. Every effort will be made to safeguard your privacy when it may be accessed by other companies, including but not limited to technology providers; however, Career Alerts will not be liable for any damages that may result from the misuse of your personal information by these companies. </p>
	<p>Career Alerts may use your IP address to administer our site. Your IP address may also be used to help identify you, your location, and to gather broad demographic information. Nothing shall restrict Career Alerts from maintaining your data following your termination of your use of Career Alerts's site. Career Alerts may delete your user data at Career Alerts's sole discretion.</p>
	<h3>Facebook Information Collection and Use</h3>
	<p>Through our use of Facebook products and services, including but not limited to Facebook Connect and Facebook Platform, we may receive personally identifiable information about you and your friends who are registered on Facebook ("Friend"). We may use this information to customize and improve the services that we provide to you. By visiting Career Alerts, information that we receive from Facebook about you and your Friends may appear on our site. In addition, if a user visits our site and you are listed as a Friend of that user on Facebook, your information may also appear on our site. You can learn more <a href="http://www.facebook.com/privacy/explanation.php">here</a>.</p>
	<h3>Email Communications</h3>
	<p>Career Alerts respects your email preferences and will never provide your email address to a third party without your permission, except as may be prescribed elsewhere in this Privacy Policy. If you provide us your email address, Career Alerts may email you job alerts, account notifications, news, offers, surveys, promotions, and other communications. If you do not want to receive particular types of email messages from Career Alerts, follow the unsubscribe instructions contained in the email message to notify us of our preferences, or click <a href="#unsubscribe">here</a>. </p>
	<h3>Children's Privacy</h3>
	<p>Career Alerts's site is not intended for and may not be used by children under the age of 13. Career Alerts is committed to protecting the privacy needs of children and we encourage parents and guardians to take an active role in their children's online activities. Career Alerts does not knowingly collect personally identifiable information from children under the age of 13, nor does Career Alerts target its services or site to children under the age of 13. We recommend that minors between the ages of 13 and 17 ask and receive permission from their parent or guardian prior to using Career Alerts or sending information about themselves or anyone else over the Internet.</p>
	<h3>Protect Yourself</h3>
	<p>Career Alerts uses automated processes and third party aggregators to collect and present information that has been created by third parties, so we cannot verify the accuracy or legitimacy of all job postings displayed on our site. We strongly encourage you to exercise caution when providing information about yourself to others online, including when you apply for jobs found on Career Alerts. </p>
	<p>Never provide your social security number, credit card information, bank account details, or unnecessary personal information to a potential employer. Never participate in a financial transaction of any sort with a potential employer. Always be cautions of opportunities that sound too good to be true or require you to act as a financial intermediary, particularly for an overseas person.</p>
	<h3>Cookies</h3>
	<p>Cookies are small pieces of information that are stored by your browser on your computers hard drive. Career Alerts may use cookies to keep track of your session and advertising delivery. Career Alerts or our partners may also use cookies to deliver content specific to your interests and to save a password associated with a user profile. We use third-party advertising companies to serve ads when you visit our site. These companies may use third-party cookies to record information (excluding your name, address, email address, or telephone number) about your visits to this and other websites in order to provide advertisements about goods and services of interest to you on others websites. You can learn more <a href="http://www.google.com/privacy/ads/" target="_blank" rel="nofollow">here</a>. You can opt-out of this type of advertising <a href="http://www.aboutads.info" target="_blank" rel="nofollow">here</a>.</p>
	<h3>Links to Third Party Sites</h3>
	<p>The Career Alerts site may provide links to external websites. Such links do not constitute an endorsement by Career Alerts of those external websites. You acknowledge that Career Alerts is providing these links to you only as a convenience, and further agree that Career Alerts is not responsible for the content of such external websites. Your use of external websites is subject to the terms of use and privacy policies located on the external websites.</p>
	<h3>Assignment</h3>
	<p>If there is a change of control in Career Alerts's business (whether by merger, sale, or otherwise) or if there is an asset sale, the user information, including personal information, could be sold as part of that transaction and your personally identifying information potentially could be used by the purchaser. However, if that business materially changes this statement or the information handling practices as described in this Privacy Policy, you will be notified by email and/or through a notice posted on the site, and you may opt-out of the use of your existing information in a new manner. This Privacy Policy inures to the benefit of any successors or assigns of Career Alerts or the assets of Career Alerts.</p>
	<h3>Conditions of Use</h3>
	<p>If you decide to use Career Alerts's site or services, your use and any possible dispute over privacy is subject to this Privacy Policy. If you have questions about this Privacy Policy, you can <a href="#contact">contact us</a>.</p>
	<h3>Contact Information</h3>
	<ul>
		<li>Career Alerts</li>
	    <li>2312 Park Ave #408</li>
	    <li>Tustin, CA 92782 USA</li>
	</ul>
</div>
<div class="subpage-footer">
	<ul>
		<li>&copy; 2014 Career Alerts</li>
		<li><a href="#getting-started">Getting Started</a></li>
		<li><a href="#faq">FAQ</a></li>
		<li><a href="#privacy">Privacy Policy</a></li>
		<li><a href="#contact">Contact Us</a></li>
	</ul>
</div>